{% set version = "3.0.1" %}

package:
  name: django-reversion
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-reversion/django-reversion-{{ version }}.tar.gz
  sha256: 98cb09c2227b14a0f88faaf4f747a716a5b1f183768959fe6035cbc12c3adbfe

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django >=1.8

test:
  imports:
    - reversion    

about:
  home: https://github.com/etianen/django-reversion
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'django-reversion is an extension to the Django web framework that 
  provides version control for model instances.'
  description: 
    django-reversion is an extension to the Django web framework that provides 
    version control for model instances.
  doc_url: https://django-reversion.readthedocs.io/en/stable/
  dev_url: https://github.com/etianen/django-reversion

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    
