travis:
  secure:
    BINSTAR_TOKEN: oo9/mZoU/tyEGLWdJWuO1QNHyJyxOyHEKxeSTnnPMo9bFmXgGsec/f3gSEgAU3sjPtsnWGwCApD31ayDodc1ITEIWYdcIw6iOE+c//dDtMp1+4ZwH8oLXBj7gtnwuEJsuiFqBbG07FWZLBp3L/hsoRILKrYPVQq1LrZDul5E23P3FOUrzjHqfLP39R38Jjov8/EwlKgMDeDyPP4aOcLaM1eq0ZkKOsBEOk0NXj/583NNVo7TjLw+um6YoukFT517Ce1RTGyuUaYDzCG36J8gKDYrG27cmXevFCAwcp6Lccv/DJb2ZGt+PT8PPfSzP4Z95cUQHLV8jrKGLMkoNd+RvHTEuG7LPOAbYfU4Y1hrhgRn85Yp5KpsyHLWt5lRzdLPw+Hls70ApwzONPNnlN0InhVg7eMOP6uz1wQzI/tWFKwdanlGrb4idbyVvwhgBcdoyb3uMpRAo4eCmaR2fH0B+WYlQ+74leygei32e7akslXEQKreOYRsKsTvTgsU5KMX1c7MSExYFgDk/3+Ye2RwYD1emVOvDuVTDf7kyj/CnFHGrBqcWN4oicvJdBzAXum3grfzlmDuR3mSFq+b4p3AL+lE6NFfzvT+TaWtJMmy/qGRLGxVkT9PJWfQUsZPI9e9s7GaptZnjbjKkio9Cr3dv++bw8MXVk6cShv75p0tLP4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
