travis:
  secure:
    BINSTAR_TOKEN: Lmwis772c2KS60D8huYSF4xIzFQvrM0nPpc7QmQMtdUzJgNhTv2Ie/kv+eq+uuZQ86tb+JNiz12vQLr7X0ZtchujbRUl/nS6D0WJ++SUwd5/Fdr0Xg3ykcgBpWkzoBvNqIRVa6V24VKrUtuWCyq0vzBH2nv4bAHY3qZWHzD8aS6qNROHB6j6mu+SlExSx5Pygnf6bNSMW+6F9XzVZN5I1jmF8KInCIKl3b77w/SlEsUzo9S0nqYSvERwT6zbfPddqKM0qwYGLV2YiTIAQc7XHbQIz9IH7Vj/aqyL8osjKRLo9DPL+xzQr/2YX1oS2fZcKhVqMp2yaTeEVJQSv5ps4hic/yMixGpGVciU7OKRwV87ajnqVJ83LJ6SBEDYluGt1Db4+D4Oh7fuptWg7UeZ2mmW4z795gcM/wozRER7DzeOrcYDhfXG88XBA9Jpmm1Xf+kisxlyZkZgTq2gAS8DhIfBgye9mcq3n5vQuQ5ryMgJFip1RKen5ohcSZOk0tI9/EZv0XgjVQXBgKdipE62kNWmBrfEfNUUVEukW7teKC9j09LA+vfNvdX8tAdyNGcOm/+Fe5TxO62tKuEj8g0qA00vxJZDA62pocdrs7lumBxKO4kVxqdkHJDQkQ4LogvA4W6ShKHlgRkLGnWEo64bNJwaJxEC5Q/2NDCF3yM76IE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
